---
name: Branch Build
on: [push]

jobs:
  build:
    name: branch_builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
      - name: Build with Gradle
        run: ./gradlew build
